"""community”

Revision ID: 2d9fcb6f990a
Revises: 973d010696ac
Create Date: 2024-07-24 02:21:00.039488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d9fcb6f990a'
down_revision: Union[str, None] = '973d010696ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('community_id', sa.Integer(), nullable=False))
    op.drop_index('ix_community_qna_id', table_name='community')
    op.create_index(op.f('ix_community_community_id'), 'community', ['community_id'], unique=False)
    op.drop_column('community', 'qna_id')
    op.add_column('community_comment', sa.Column('community_comment_id', sa.Integer(), nullable=False))
    op.add_column('community_comment', sa.Column('community_id', sa.Integer(), nullable=False))
    op.drop_index('ix_community_comment_comment_id', table_name='community_comment')
    op.create_index(op.f('ix_community_comment_community_comment_id'), 'community_comment', ['community_comment_id'], unique=False)
    op.drop_constraint('community_comment_ibfk_1', 'community_comment', type_='foreignkey')
    op.create_foreign_key(None, 'community_comment', 'community', ['community_id'], ['community_id'])
    op.drop_column('community_comment', 'comment_id')
    op.drop_column('community_comment', 'qna_id')
    op.add_column('community_image', sa.Column('community_id', sa.Integer(), nullable=True))
    op.add_column('community_image', sa.Column('community_comment_id', sa.Integer(), nullable=True))
    op.drop_index('ix_Community_image_image_id', table_name='community_image')
    op.create_index(op.f('ix_community_image_image_id'), 'community_image', ['image_id'], unique=False)
    op.drop_constraint('community_image_ibfk_2', 'community_image', type_='foreignkey')
    op.drop_constraint('community_image_ibfk_1', 'community_image', type_='foreignkey')
    op.create_foreign_key(None, 'community_image', 'community', ['community_id'], ['community_id'])
    op.create_foreign_key(None, 'community_image', 'community_comment', ['community_comment_id'], ['community_comment_id'])
    op.drop_column('community_image', 'comment_id')
    op.drop_column('community_image', 'qna_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_image', sa.Column('qna_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('community_image', sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'community_image', type_='foreignkey')
    op.drop_constraint(None, 'community_image', type_='foreignkey')
    op.create_foreign_key('community_image_ibfk_1', 'community_image', 'qna', ['qna_id'], ['qna_id'])
    op.create_foreign_key('community_image_ibfk_2', 'community_image', 'comment', ['comment_id'], ['comment_id'])
    op.drop_index(op.f('ix_community_image_image_id'), table_name='community_image')
    op.create_index('ix_Community_image_image_id', 'community_image', ['image_id'], unique=False)
    op.drop_column('community_image', 'community_comment_id')
    op.drop_column('community_image', 'community_id')
    op.add_column('community_comment', sa.Column('qna_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('community_comment', sa.Column('comment_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'community_comment', type_='foreignkey')
    op.create_foreign_key('community_comment_ibfk_1', 'community_comment', 'qna', ['qna_id'], ['qna_id'])
    op.drop_index(op.f('ix_community_comment_community_comment_id'), table_name='community_comment')
    op.create_index('ix_community_comment_comment_id', 'community_comment', ['comment_id'], unique=False)
    op.drop_column('community_comment', 'community_id')
    op.drop_column('community_comment', 'community_comment_id')
    op.add_column('community', sa.Column('qna_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_community_community_id'), table_name='community')
    op.create_index('ix_community_qna_id', 'community', ['qna_id'], unique=False)
    op.drop_column('community', 'community_id')
    # ### end Alembic commands ###
