"""schema change”

Revision ID: 2e0b96d38d5d
Revises: 02994275cd1a
Create Date: 2024-07-14 18:26:46.799136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e0b96d38d5d'
down_revision: Union[str, None] = '02994275cd1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('docs_id', sa.Integer(), nullable=False))
    op.drop_index('ix_docs_dics_id', table_name='docs')
    op.create_index(op.f('ix_docs_docs_id'), 'docs', ['docs_id'], unique=False)
    op.drop_column('docs', 'dics_id')
    op.add_column('user_info', sa.Column('user_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_info_user_name'), 'user_info', ['user_name'], unique=False)
    op.drop_index('ix_users_user_name', table_name='users')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_users_user_name', 'users', ['user_name'], unique=False)
    op.drop_index(op.f('ix_user_info_user_name'), table_name='user_info')
    op.drop_column('user_info', 'user_name')
    op.add_column('docs', sa.Column('dics_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_docs_docs_id'), table_name='docs')
    op.create_index('ix_docs_dics_id', 'docs', ['dics_id'], unique=False)
    op.drop_column('docs', 'docs_id')
    # ### end Alembic commands ###
