"""new schema”

Revision ID: 8998e7070e52
Revises: d12e05de07b6
Create Date: 2024-07-04 15:12:12.595901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8998e7070e52'
down_revision: Union[str, None] = 'd12e05de07b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_auth', 'name')
    op.drop_column('image', 'image_path')
    op.drop_column('qna', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qna', sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('image', sa.Column('image_path', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('email_auth', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
