"""signup modify

Revision ID: 8f20467982db
Revises: 5f0a01043131
Create Date: 2024-07-02 14:46:56.737723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f20467982db'
down_revision: Union[str, None] = '5f0a01043131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAQ',
    sa.Column('faq_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_index(op.f('ix_FAQ_faq_id'), 'FAQ', ['faq_id'], unique=False)
    op.drop_index('ix_FAQ_faq_id', table_name='faq')
    op.drop_table('faq')
    op.add_column('user_info', sa.Column('position', sa.String(length=100), nullable=True))
    op.drop_index('ix_user_info_name', table_name='user_info')
    op.drop_column('user_info', 'name')
    op.add_column('users', sa.Column('user_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_column('users', 'user_name')
    op.add_column('user_info', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('ix_user_info_name', 'user_info', ['name'], unique=False)
    op.drop_column('user_info', 'position')
    op.create_table('faq',
    sa.Column('faq_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faq_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_FAQ_faq_id', 'faq', ['faq_id'], unique=False)
    op.drop_index(op.f('ix_FAQ_faq_id'), table_name='FAQ')
    op.drop_table('FAQ')
    # ### end Alembic commands ###
