"""add table

Revision ID: 946ea6979424
Revises: d3e0f6f5fd2e
Create Date: 2024-06-29 19:24:06.534523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '946ea6979424'
down_revision: Union[str, None] = 'd3e0f6f5fd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAQ',
    sa.Column('faq_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_index(op.f('ix_FAQ_faq_id'), 'FAQ', ['faq_id'], unique=False)
    op.drop_index('ix_FAQ_faq_id', table_name='faq')
    op.drop_table('faq')
    op.add_column('email_auth', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_auth', 'updated_at')
    op.create_table('faq',
    sa.Column('faq_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faq_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_FAQ_faq_id', 'faq', ['faq_id'], unique=False)
    op.drop_index(op.f('ix_FAQ_faq_id'), table_name='FAQ')
    op.drop_table('FAQ')
    # ### end Alembic commands ###
