"""new schema”

Revision ID: bdb51b6a7408
Revises: 8f20467982db
Create Date: 2024-07-04 10:58:25.819197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bdb51b6a7408'
down_revision: Union[str, None] = '8f20467982db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('qna_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('image_name', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.comment_id'], ),
    sa.ForeignKeyConstraint(['qna_id'], ['qna.qna_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_image_image_id'), 'image', ['image_id'], unique=False)
    op.drop_index('ix_news_news_id', table_name='news')
    op.drop_table('news')
    op.drop_index('ix_FAQ_faq_id', table_name='faq')
    op.drop_table('faq')
    op.drop_index('ix_state_state_id', table_name='state')
    op.drop_table('state')
    op.drop_index('ix_chat_chat_id', table_name='chat')
    op.drop_table('chat')
    op.drop_index('ix_board_board_id', table_name='board')
    op.drop_table('board')
    op.drop_index('ix_country_country_id', table_name='country')
    op.drop_table('country')
    op.drop_index('ix_keyword_keyword_id', table_name='keyword')
    op.drop_table('keyword')
    op.add_column('comment', sa.Column('comment_id', sa.Integer(), nullable=False))
    op.add_column('comment', sa.Column('qna_id', sa.Integer(), nullable=False))
    op.alter_column('comment', 'created_at',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_comment_reply_id', table_name='comment')
    op.create_index(op.f('ix_comment_comment_id'), 'comment', ['comment_id'], unique=False)
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'qna', ['qna_id'], ['qna_id'])
    op.drop_column('comment', 'board_id')
    op.drop_column('comment', 'reply_id')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('comment', sa.Column('reply_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('comment', sa.Column('board_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'board', ['board_id'], ['board_id'])
    op.drop_index(op.f('ix_comment_comment_id'), table_name='comment')
    op.create_index('ix_comment_reply_id', 'comment', ['reply_id'], unique=False)
    op.alter_column('comment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('comment', 'qna_id')
    op.drop_column('comment', 'comment_id')
    op.create_table('keyword',
    sa.Column('keyword_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('keyword', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], name='keyword_ibfk_1'),
    sa.PrimaryKeyConstraint('keyword_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_keyword_keyword_id', 'keyword', ['keyword_id'], unique=False)
    op.create_table('country',
    sa.Column('country_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('country_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_country_country_id', 'country', ['country_id'], unique=False)
    op.create_table('board',
    sa.Column('board_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], name='board_ibfk_1'),
    sa.PrimaryKeyConstraint('board_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_board_board_id', 'board', ['board_id'], unique=False)
    op.create_table('chat',
    sa.Column('chat_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Field6', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], name='chat_ibfk_1'),
    sa.PrimaryKeyConstraint('chat_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_chat_chat_id', 'chat', ['chat_id'], unique=False)
    op.create_table('state',
    sa.Column('state_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], name='state_ibfk_1'),
    sa.PrimaryKeyConstraint('state_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_state_state_id', 'state', ['state_id'], unique=False)
    op.create_table('faq',
    sa.Column('faq_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faq_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_FAQ_faq_id', 'faq', ['faq_id'], unique=False)
    op.create_table('news',
    sa.Column('news_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], name='news_ibfk_2'),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], name='news_ibfk_1'),
    sa.PrimaryKeyConstraint('news_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_news_news_id', 'news', ['news_id'], unique=False)
    op.drop_index(op.f('ix_image_image_id'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
