"""Initial migration

Revision ID: c604e06a9a7c
Revises: 
Create Date: 2024-06-26 13:29:15.976315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c604e06a9a7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAQ',
    sa.Column('faq_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_index(op.f('ix_FAQ_faq_id'), 'FAQ', ['faq_id'], unique=False)
    op.drop_index('ix_FAQ_faq_id', table_name='faq')
    op.drop_table('faq')
    op.add_column('user_info', sa.Column('user_info_id', sa.Integer(), nullable=False))
    op.alter_column('user_info', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_user_info_email', table_name='user_info')
    op.create_index(op.f('ix_user_info_email'), 'user_info', ['email'], unique=True)
    op.create_index(op.f('ix_user_info_user_info_id'), 'user_info', ['user_info_id'], unique=False)
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.drop_column('users', 'id')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'password')
    op.drop_column('users', 'user_id')
    op.drop_index(op.f('ix_user_info_user_info_id'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_email'), table_name='user_info')
    op.create_index('ix_user_info_email', 'user_info', ['email'], unique=False)
    op.alter_column('user_info', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user_info', 'user_info_id')
    op.create_table('faq',
    sa.Column('faq_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faq_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_FAQ_faq_id', 'faq', ['faq_id'], unique=False)
    op.drop_index(op.f('ix_FAQ_faq_id'), table_name='FAQ')
    op.drop_table('FAQ')
    # ### end Alembic commands ###
