"""add faq table

Revision ID: cc370a116357
Revises: c405890b02c6
Create Date: 2024-06-28 16:47:19.469924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc370a116357'
down_revision: Union[str, None] = 'c405890b02c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FAQ',
    sa.Column('faq_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_index(op.f('ix_FAQ_faq_id'), 'FAQ', ['faq_id'], unique=False)
    op.drop_index('ix_FAQ_faq_id', table_name='faq')
    op.drop_table('faq')
    op.alter_column('board', 'board_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat', 'chat_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('comment', 'reply_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('comment', 'board_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('country', 'country_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('email_auth', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('email_auth', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('email_auth', sa.Column('verify_number', sa.String(length=10), nullable=False))
    op.add_column('email_auth', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('email_auth', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_email_auth_email'), 'email_auth', ['email'], unique=True)
    op.create_index(op.f('ix_email_auth_emailAuth_id'), 'email_auth', ['emailAuth_id'], unique=False)
    op.alter_column('keyword', 'keyword_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('news', 'news_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('news', 'state_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('news', 'country_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('state', 'state_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('state', 'country_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('state', 'country_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('state', 'state_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('news', 'country_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('news', 'state_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('news', 'news_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('keyword', 'keyword_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_email_auth_emailAuth_id'), table_name='email_auth')
    op.drop_index(op.f('ix_email_auth_email'), table_name='email_auth')
    op.drop_column('email_auth', 'created_at')
    op.drop_column('email_auth', 'is_active')
    op.drop_column('email_auth', 'verify_number')
    op.drop_column('email_auth', 'email')
    op.drop_column('email_auth', 'name')
    op.alter_column('country', 'country_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('comment', 'board_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('comment', 'reply_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chat', 'chat_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('board', 'board_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('faq',
    sa.Column('faq_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faq_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_FAQ_faq_id', 'faq', ['faq_id'], unique=False)
    op.drop_index(op.f('ix_FAQ_faq_id'), table_name='FAQ')
    op.drop_table('FAQ')
    # ### end Alembic commands ###
