"""new schema”

Revision ID: d12e05de07b6
Revises: 340e8f286de9
Create Date: 2024-07-04 11:18:10.741601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12e05de07b6'
down_revision: Union[str, None] = '340e8f286de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_auth',
    sa.Column('emailAuth_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('verify_number', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('emailAuth_id')
    )
    op.create_index(op.f('ix_email_auth_email'), 'email_auth', ['email'], unique=True)
    op.create_index(op.f('ix_email_auth_emailAuth_id'), 'email_auth', ['emailAuth_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.create_table('qna',
    sa.Column('qna_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('qna_id')
    )
    op.create_index(op.f('ix_qna_qna_id'), 'qna', ['qna_id'], unique=False)
    op.create_table('user_info',
    sa.Column('user_info_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('corporation', sa.String(length=255), nullable=True),
    sa.Column('business_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('user_info_id')
    )
    op.create_index(op.f('ix_user_info_email'), 'user_info', ['email'], unique=True)
    op.create_index(op.f('ix_user_info_user_info_id'), 'user_info', ['user_info_id'], unique=False)
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('qna_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['qna_id'], ['qna.qna_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comment_comment_id'), 'comment', ['comment_id'], unique=False)
    op.create_table('image',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('qna_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('image_name', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.comment_id'], ),
    sa.ForeignKeyConstraint(['qna_id'], ['qna.qna_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_image_image_id'), 'image', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_image_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_comment_comment_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_user_info_user_info_id'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_email'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_index(op.f('ix_qna_qna_id'), table_name='qna')
    op.drop_table('qna')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_email_auth_emailAuth_id'), table_name='email_auth')
    op.drop_index(op.f('ix_email_auth_email'), table_name='email_auth')
    op.drop_table('email_auth')
    # ### end Alembic commands ###
